### ISSUE TITLE
Could not log in

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/uui#36]
Logging in with a brand  new name nothing happens.

Console had this error:

Uncaught TypeError: Cannot read property 'USERID' of undefined
    at handleSelectUserResponse (file_manager.js:619)
    at HandleLoginCallback (index.html:1161)
    at Object.success (file_manager.js:651)
    at i (jquery-3.2.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.2.1.min.js:2)
    at A (jquery-3.2.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.2.1.min.js:4)
    at XMLHttpRequest.d (raven.js:425)
    at XMLHttpRequest.send (raven.js:1297)
    at Object.send (jquery-3.2.1.min.js:4)
    at Function.ajax (jquery-3.2.1.min.js:4)
    at makeAjaxCall (file_manager.js:637)
    at selectUser (file_manager.js:263)
    at HandleUserLogin (index.html:1158)
    at HTMLButtonElement.onclick (VM860 index.html:1125)

When I placed an x in the session id area I got an alert but then all was well.

**Comment by afsheenam** [comment]
This should be fixed now. Can you please try again an let me know

**Comment by ToonTalk** [comment]
I'm still having this problem. I just entered xxx as my user name and clicked on login.

**Comment by ToonTalk** [comment]
Works fine now.
